# Generated by Django 5.2.9 on 2026-01-07 16:23

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_writer_twitter_artist_email_writer_cashtag'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='content.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_reads',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='article_rea_user_id_02650e_idx'), models.Index(fields=['article'], name='article_rea_article_7e8e83_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='content.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_articles',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', 'saved_at'], name='saved_artic_user_id_23b26d_idx'), models.Index(fields=['article'], name='saved_artic_article_0b80c8_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
