# Generated by Django 5.2.9 on 2026-01-06 18:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('COUNTRY', 'Country'), ('EDM', 'EDM'), ('HARDCORE & ROCK', 'Hardcore & Rock'), ('HIP-HOP & R&B', 'Hip-Hop & R&B'), ('OTHER', 'Other')], max_length=50)),
                ('excerpt', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('cover_image', models.ImageField(upload_to='articles/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('location', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Country', 'Country'), ('EDM', 'EDM'), ('Hardcore & Rock', 'Hardcore & Rock'), ('Hip-Hop & R&B', 'Hip-Hop & R&B'), ('Other', 'Other')], max_length=50)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('spotify_artist_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('profile_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('venue', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('ticket_link', models.URLField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(choices=[('COUNTRY', 'Country'), ('EDM', 'EDM'), ('HARDCORE & ROCK', 'Hardcore & Rock'), ('HIP-HOP & R&B', 'Hip-Hop & R&B'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('past', 'Past')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_artists',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='writers/')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'writers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_artists', to='content.article')),
            ],
            options={
                'db_table': 'article_artists',
            },
        ),
    ]
