# Generated by Django 5.2.9 on 2026-01-06 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_artists', to='content.artist'),
        ),
        migrations.AddField(
            model_name='article',
            name='artists',
            field=models.ManyToManyField(related_name='articles', through='content.ArticleArtist', to='content.artist'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_artists', to='content.artist'),
        ),
        migrations.AddField(
            model_name='eventartist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_artists', to='content.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', through='content.EventArtist', to='content.artist'),
        ),
        migrations.AddField(
            model_name='writer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.writer'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['slug'], name='artists_slug_91e4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['genre'], name='artists_genre_74d62b_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['claimed'], name='artists_claimed_f55d70_idx'),
        ),
        migrations.AddIndex(
            model_name='articleartist',
            index=models.Index(fields=['article'], name='article_art_article_df687c_idx'),
        ),
        migrations.AddIndex(
            model_name='articleartist',
            index=models.Index(fields=['artist'], name='article_art_artist__bbefd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articleartist',
            unique_together={('article', 'artist')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article'], name='comments_article_1a27b2_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comments_created_d5740c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventartist',
            index=models.Index(fields=['event'], name='event_artis_event_i_acd49b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventartist',
            index=models.Index(fields=['artist'], name='event_artis_artist__6e72b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventartist',
            unique_together={('event', 'artist')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_slug_930801_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['genre'], name='events_genre_4a70fc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_date_e70fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_created_2c88fa_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_slug_c8b0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='articles_categor_052161_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_status_a4f178_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='articles_publish_73ad5f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='articles_author__a0ff4a_idx'),
        ),
    ]
