# Generated by Django 5.2.9 on 2026-01-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='twitter',
        ),
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, help_text='Email to send claim invitation', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='cashtag',
            field=models.CharField(blank=True, help_text='Cash App cashtag (e.g., $username)', max_length=50, null=True),
        ),
    ]
