import { defineConfig } from "vite-plus";

export default defineConfig({
  fmt: {
    ignorePatterns: ["apps/arts/src/routeTree.gen.ts"],
  },
  lint: {
    plugins: ["unicorn", "typescript", "oxc"],
    categories: {},
    rules: {
      "constructor-super": "warn",
      "for-direction": "warn",
      "no-async-promise-executor": "warn",
      "no-caller": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "warn",
      "no-constant-binary-expression": "warn",
      "no-constant-condition": "warn",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-delete-var": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-else-if": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-empty-static-block": "warn",
      "no-eval": "warn",
      "no-ex-assign": "warn",
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-loss-of-precision": "warn",
      "no-new-native-nonconstructor": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-self-assign": "warn",
      "no-setter-return": "warn",
      "no-shadow-restricted-names": "warn",
      "no-sparse-arrays": "warn",
      "no-this-before-super": "warn",
      "no-unassigned-vars": "warn",
      "no-unsafe-finally": "warn",
      "no-unsafe-negation": "warn",
      "no-unsafe-optional-chaining": "warn",
      "no-unused-expressions": "warn",
      "no-unused-labels": "warn",
      "no-unused-private-class-members": "warn",
      "no-unused-vars": "warn",
      "no-useless-backreference": "warn",
      "no-useless-catch": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-with": "warn",
      "require-yield": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",
      "oxc/bad-array-method-on-arguments": "warn",
      "oxc/bad-char-at-comparison": "warn",
      "oxc/bad-comparison-sequence": "warn",
      "oxc/bad-min-max-func": "warn",
      "oxc/bad-object-literal-comparison": "warn",
      "oxc/bad-replace-all-arg": "warn",
      "oxc/const-comparisons": "warn",
      "oxc/double-comparisons": "warn",
      "oxc/erasing-op": "warn",
      "oxc/missing-throw": "warn",
      "oxc/number-arg-out-of-range": "warn",
      "oxc/only-used-in-recursion": "warn",
      "oxc/uninvoked-array-callback": "warn",
      "typescript/await-thenable": "warn",
      "typescript/no-array-delete": "warn",
      "typescript/no-base-to-string": "warn",
      "typescript/no-duplicate-enum-values": "warn",
      "typescript/no-duplicate-type-constituents": "warn",
      "typescript/no-extra-non-null-assertion": "warn",
      "typescript/no-floating-promises": "warn",
      "typescript/no-for-in-array": "warn",
      "typescript/no-implied-eval": "warn",
      "typescript/no-meaningless-void-operator": "warn",
      "typescript/no-misused-new": "warn",
      "typescript/no-misused-spread": "warn",
      "typescript/no-non-null-asserted-optional-chain": "warn",
      "typescript/no-redundant-type-constituents": "warn",
      "typescript/no-this-alias": "warn",
      "typescript/no-unnecessary-parameter-property-assignment": "warn",
      "typescript/no-unsafe-declaration-merging": "warn",
      "typescript/no-unsafe-unary-minus": "warn",
      "typescript/no-useless-empty-export": "warn",
      "typescript/no-wrapper-object-types": "warn",
      "typescript/prefer-as-const": "warn",
      "typescript/require-array-sort-compare": "warn",
      "typescript/restrict-template-expressions": "warn",
      "typescript/triple-slash-reference": "warn",
      "typescript/unbound-method": "warn",
      "unicorn/no-await-in-promise-methods": "warn",
      "unicorn/no-empty-file": "warn",
      "unicorn/no-invalid-fetch-options": "warn",
      "unicorn/no-invalid-remove-event-listener": "warn",
      "unicorn/no-new-array": "warn",
      "unicorn/no-single-promise-in-promise-methods": "warn",
      "unicorn/no-thenable": "warn",
      "unicorn/no-unnecessary-await": "warn",
      "unicorn/no-useless-fallback-in-spread": "warn",
      "unicorn/no-useless-length-check": "warn",
      "unicorn/no-useless-spread": "warn",
      "unicorn/prefer-set-size": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      complexity: "off",
      "func-names": "off",
      "func-style": "off",
      "max-depth": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "off",
      "max-params": "off",
      "max-statements": "off",
      "class-methods-use-this": "off",
      "default-case": "off",
      eqeqeq: "off",
      "import/first": "off",
      "import/no-duplicates": "off",
      "import/no-named-as-default": "off",
      "import/no-relative-parent-imports": "off",
      "jest/max-expects": "off",
      "jest/no-conditional-expect": "off",
      "jest/no-conditional-in-test": "off",
      "jest/no-hooks": "off",
      "jest/prefer-mock-return-shorthand": "off",
      "jest/prefer-spy-on": "off",
      "jest/require-hook": "off",
      "jest/require-top-level-describe": "off",
      "jest/valid-title": "off",
      "jsdoc/require-param-type": "off",
      "jsdoc/require-returns-type": "off",
      "no-bitwise": "off",
      "no-duplicate-imports": "off",
      "no-empty-function": "off",
      "no-eq-null": "off",
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-param-reassign": "off",
      "no-plusplus": "off",
      "no-shadow": "off",
      "no-use-before-define": "off",
      "no-useless-return": "off",
      "no-void": "off",
      "no-warning-comments": "off",
      "oxc/no-accumulating-spread": "off",
      "prefer-destructuring": "off",
      "prefer-template": "off",
      "promise/prefer-await-to-callbacks": "off",
      "promise/prefer-await-to-then": "off",
      radix: "off",
      "require-await": "off",
      "sort-keys": "off",
      "typescript/ban-ts-comment": "off",
      "typescript/consistent-type-imports": "off",
      "typescript/no-explicit-any": "off",
      "typescript/no-inferrable-types": "off",
      "typescript/no-invalid-void-type": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/filename-case": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/no-await-expression-member": "off",
      "unicorn/no-document-cookie": "off",
      "unicorn/no-lonely-if": "off",
      "unicorn/no-nested-ternary": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/no-useless-switch-case": "off",
      "unicorn/prefer-array-find": "off",
      "unicorn/prefer-default-parameters": "off",
      "unicorn/prefer-module": "off",
      "unicorn/prefer-native-coercion-functions": "off",
      "unicorn/prefer-object-from-entries": "off",
      "unicorn/prefer-ternary": "off",
      "vitest/consistent-test-filename": "off",
      "vitest/require-mock-type-parameters": "off",
      "vitest/valid-title": "off",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    overrides: [
      {
        files: ["**/*.{test,spec}.{ts,tsx,js,jsx}", "**/__tests__/**/*.{ts,tsx,js,jsx}"],
        plugins: ["jest", "vitest"],
        rules: {
          "jest/max-expects": "off",
          "jest/no-conditional-expect": "off",
          "jest/no-conditional-in-test": "off",
          "jest/no-hooks": "off",
          "jest/prefer-mock-return-shorthand": "off",
          "jest/prefer-spy-on": "off",
          "jest/require-hook": "off",
          "jest/require-top-level-describe": "off",
          "jest/valid-title": "off",
          "vitest/prefer-called-once": "off",
          "vitest/consistent-test-filename": "off",
          "vitest/require-mock-type-parameters": "off",
          "vitest/valid-title": "off",
        },
      },
      {
        files: ["apps/arts/src/routeTree.gen.ts"],
        rules: {
          "unicorn/no-abusive-eslint-disable": "off",
        },
      },
    ],
    settings: {
      "jsx-a11y": {
        polymorphicPropName: null,
        components: {},
        attributes: {},
      },
      next: {
        rootDir: [],
      },
      react: {
        formComponents: [],
        linkComponents: [],
        version: null,
      },
      jsdoc: {
        ignorePrivate: false,
        ignoreInternal: false,
        ignoreReplacesDocs: true,
        overrideReplacesDocs: true,
        augmentsExtendsReplacesDocs: false,
        implementsReplacesDocs: false,
        exemptDestructuredRootsFromChecks: false,
        tagNamePreference: {},
      },
      vitest: {
        typecheck: false,
      },
    },
    env: {
      builtin: true,
    },
    globals: {},
    ignorePatterns: [],
    options: {
      typeAware: false,
      typeCheck: false,
    },
    jsPlugins: [
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
  },
});
