/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArtmakersRouteImport } from './routes/artmakers'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardArtworksRouteImport } from './routes/dashboard.artworks'
import { Route as ArtmakersSlugRouteImport } from './routes/artmakers.$slug'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminExhibitionsRouteImport } from './routes/admin.exhibitions'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminArtmakersRouteImport } from './routes/admin.artmakers'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminEventsImportRouteImport } from './routes/admin.events.import'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtmakersRoute = ArtmakersRouteImport.update({
  id: '/artmakers',
  path: '/artmakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArtworksRoute = DashboardArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => DashboardRoute,
} as any)
const ArtmakersSlugRoute = ArtmakersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtmakersRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExhibitionsRoute = AdminExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtmakersRoute = AdminArtmakersRouteImport.update({
  id: '/artmakers',
  path: '/artmakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsImportRoute = AdminEventsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRoute
  '/artmakers': typeof ArtmakersRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/merch': typeof MerchRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/artmakers': typeof AdminArtmakersRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/exhibitions': typeof AdminExhibitionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/upload': typeof ApiUploadRoute
  '/artmakers/$slug': typeof ArtmakersSlugRoute
  '/dashboard/artworks': typeof DashboardArtworksRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/import': typeof AdminEventsImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRoute
  '/artmakers': typeof ArtmakersRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/merch': typeof MerchRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/artmakers': typeof AdminArtmakersRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/exhibitions': typeof AdminExhibitionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/upload': typeof ApiUploadRoute
  '/artmakers/$slug': typeof ArtmakersSlugRoute
  '/dashboard/artworks': typeof DashboardArtworksRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin': typeof AdminIndexRoute
  '/admin/events/import': typeof AdminEventsImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRoute
  '/artmakers': typeof ArtmakersRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/merch': typeof MerchRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/artmakers': typeof AdminArtmakersRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/exhibitions': typeof AdminExhibitionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/upload': typeof ApiUploadRoute
  '/artmakers/$slug': typeof ArtmakersSlugRoute
  '/dashboard/artworks': typeof DashboardArtworksRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/events/import': typeof AdminEventsImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/artmakers'
    | '/dashboard'
    | '/events'
    | '/exhibitions'
    | '/merch'
    | '/onboarding'
    | '/admin/articles'
    | '/admin/artmakers'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/users'
    | '/api/upload'
    | '/artmakers/$slug'
    | '/dashboard/artworks'
    | '/dashboard/events'
    | '/dashboard/profile'
    | '/admin/'
    | '/admin/events/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/artmakers'
    | '/dashboard'
    | '/events'
    | '/exhibitions'
    | '/merch'
    | '/onboarding'
    | '/admin/articles'
    | '/admin/artmakers'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/users'
    | '/api/upload'
    | '/artmakers/$slug'
    | '/dashboard/artworks'
    | '/dashboard/events'
    | '/dashboard/profile'
    | '/admin'
    | '/admin/events/import'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/artmakers'
    | '/dashboard'
    | '/events'
    | '/exhibitions'
    | '/merch'
    | '/onboarding'
    | '/admin/articles'
    | '/admin/artmakers'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/users'
    | '/api/upload'
    | '/artmakers/$slug'
    | '/dashboard/artworks'
    | '/dashboard/events'
    | '/dashboard/profile'
    | '/admin/'
    | '/admin/events/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRoute
  ArtmakersRoute: typeof ArtmakersRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  MerchRoute: typeof MerchRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artmakers': {
      id: '/artmakers'
      path: '/artmakers'
      fullPath: '/artmakers'
      preLoaderRoute: typeof ArtmakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/artworks': {
      id: '/dashboard/artworks'
      path: '/artworks'
      fullPath: '/dashboard/artworks'
      preLoaderRoute: typeof DashboardArtworksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/artmakers/$slug': {
      id: '/artmakers/$slug'
      path: '/$slug'
      fullPath: '/artmakers/$slug'
      preLoaderRoute: typeof ArtmakersSlugRouteImport
      parentRoute: typeof ArtmakersRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exhibitions': {
      id: '/admin/exhibitions'
      path: '/exhibitions'
      fullPath: '/admin/exhibitions'
      preLoaderRoute: typeof AdminExhibitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artmakers': {
      id: '/admin/artmakers'
      path: '/artmakers'
      fullPath: '/admin/artmakers'
      preLoaderRoute: typeof AdminArtmakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/import': {
      id: '/admin/events/import'
      path: '/import'
      fullPath: '/admin/events/import'
      preLoaderRoute: typeof AdminEventsImportRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsImportRoute: typeof AdminEventsImportRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsImportRoute: AdminEventsImportRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminArtmakersRoute: typeof AdminArtmakersRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminExhibitionsRoute: typeof AdminExhibitionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminArtmakersRoute: AdminArtmakersRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminExhibitionsRoute: AdminExhibitionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArtmakersRouteChildren {
  ArtmakersSlugRoute: typeof ArtmakersSlugRoute
}

const ArtmakersRouteChildren: ArtmakersRouteChildren = {
  ArtmakersSlugRoute: ArtmakersSlugRoute,
}

const ArtmakersRouteWithChildren = ArtmakersRoute._addFileChildren(
  ArtmakersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardArtworksRoute: typeof DashboardArtworksRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArtworksRoute: DashboardArtworksRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRoute,
  ArtmakersRoute: ArtmakersRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  MerchRoute: MerchRoute,
  OnboardingRoute: OnboardingRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
