/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArtmakersRouteImport } from './routes/artmakers'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtmakersSlugRouteImport } from './routes/artmakers.$slug'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtmakersRoute = ArtmakersRouteImport.update({
  id: '/artmakers',
  path: '/artmakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtmakersSlugRoute = ArtmakersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtmakersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/artmakers': typeof ArtmakersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/onboarding': typeof OnboardingRoute
  '/artmakers/$slug': typeof ArtmakersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/artmakers': typeof ArtmakersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/onboarding': typeof OnboardingRoute
  '/artmakers/$slug': typeof ArtmakersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/articles': typeof ArticlesRoute
  '/artmakers': typeof ArtmakersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/onboarding': typeof OnboardingRoute
  '/artmakers/$slug': typeof ArtmakersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/artmakers'
    | '/dashboard'
    | '/events'
    | '/onboarding'
    | '/artmakers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/articles'
    | '/artmakers'
    | '/dashboard'
    | '/events'
    | '/onboarding'
    | '/artmakers/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/artmakers'
    | '/dashboard'
    | '/events'
    | '/onboarding'
    | '/artmakers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArticlesRoute: typeof ArticlesRoute
  ArtmakersRoute: typeof ArtmakersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artmakers': {
      id: '/artmakers'
      path: '/artmakers'
      fullPath: '/artmakers'
      preLoaderRoute: typeof ArtmakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artmakers/$slug': {
      id: '/artmakers/$slug'
      path: '/$slug'
      fullPath: '/artmakers/$slug'
      preLoaderRoute: typeof ArtmakersSlugRouteImport
      parentRoute: typeof ArtmakersRoute
    }
  }
}

interface ArtmakersRouteChildren {
  ArtmakersSlugRoute: typeof ArtmakersSlugRoute
}

const ArtmakersRouteChildren: ArtmakersRouteChildren = {
  ArtmakersSlugRoute: ArtmakersSlugRoute,
}

const ArtmakersRouteWithChildren = ArtmakersRoute._addFileChildren(
  ArtmakersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArticlesRoute: ArticlesRoute,
  ArtmakersRoute: ArtmakersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
